# Generated by Django 6.1.1 on 2026-09-15 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='faultevent',
            new_name='network_fau_device__b8227f_idx',
            old_name='network_fau_device__f6c5a5_idx',
        ),
        migrations.RenameIndex(
            model_name='faultevent',
            new_name='network_fau_status_7e232f_idx',
            old_name='network_fau_status_4db0f0_idx',
        ),
        migrations.RenameIndex(
            model_name='monitoringrecord',
            new_name='network_mon_device__44e2a3_idx',
            old_name='network_mon_device__fbe5f0_idx',
        ),
    ]
