# Generated by Django 6.1.1 on 2026-09-15 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_rename_network_fau_device__f6c5a5_idx_network_fau_device__b8227f_idx_and_more'),
        ('network', '0002_rename_type_device_device_type'),
    ]

    operations = [
    ]
