# Generated by Django 6.1.1 on 2026-09-15 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_snmpmonitoring'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='snmpmetric',
            new_name='network_snm_device__28657a_idx',
            old_name='network_snm_device__f4d2a4_idx',
        ),
        migrations.RenameIndex(
            model_name='snmpmetric',
            new_name='network_snm_device__084482_idx',
            old_name='network_snm_device__4f20ab_idx',
        ),
    ]
