# Generated by Django 6.1.1 on 2026-09-15 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_fault_history_indexes'),
        ('network', '0007_faultevent_active_unique'),
    ]

    operations = [
    ]
